services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebook/example.ipynb:/home/jovyan/example.ipynb
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
